name: Run Checker
on:
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
   #- cron:  '*/15 * * * *'

jobs:
  checker:
    name: Check
    runs-on: ubuntu-latest
    env:
      PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot.png
          path: screenshot.png
